# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-20 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190920_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
    ]
