# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-20 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190920_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='watch',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='case',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='gem',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='plate',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='strap',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
