# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190920_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cid',
        ),
        migrations.AddField(
            model_name='order',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
